/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated catalog of cities (id and name only, no weather data). */
        get: operations["getCities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current weather for a page of cities. Pages over the same alphabetical city ordering as GET /api/cities -- request the same page number from both to line up city catalog and weather data. */
        get: operations["getCurrentWeather"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CityListResponse: {
            metadata: components["schemas"]["PageMetadata"];
            cities: components["schemas"]["CityRef"][];
        };
        CityRef: {
            /**
             * Format: int64
             * @example 42
             */
            id: number;
            /** @example Berryham-upon-Wicket */
            name: string;
        };
        WeatherListResponse: {
            metadata: components["schemas"]["WeatherPageMetadata"];
            cities: components["schemas"]["CitySummary"][];
        };
        WeatherPageMetadata: {
            /** @example 1 */
            page: number;
            /** @example 25 */
            pageSize: number;
        };
        PageMetadata: {
            /** @example 1 */
            page: number;
            /** @example 25 */
            pageSize: number;
            /** @example 100 */
            totalCities: number;
        };
        CitySummary: {
            /**
             * Format: int64
             * @example 42
             */
            id: number;
            /** @example Berryham-upon-Wicket */
            name: string;
            /**
             * Format: double
             * @description Mean temperature in °C over the past hour, null if no readings.
             * @example 23.4
             */
            temperature?: number | null;
            /**
             * Format: double
             * @description Not populated yet -- always null until wind measurements land.
             */
            windSpeed?: number | null;
            /** @description Not populated yet -- always null until wind measurements land. */
            windDirection?: number | null;
            /** @description Warnings active at query time. Always empty until weather warnings land. */
            warnings: components["schemas"]["Warning"][];
        };
        Warning: {
            /** @example High winds */
            description: string;
            /** @example yellow */
            severity: string;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCities: {
        parameters: {
            query: {
                page: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of cities. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityListResponse"];
                };
            };
        };
    };
    getCurrentWeather: {
        parameters: {
            query: {
                page: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of cities with their current weather. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherListResponse"];
                };
            };
        };
    };
}
