spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/weather
    username: weather
    password: weather
  rabbitmq:
    host: localhost
    port: 5672
    username: weather
    password: weather

weather:
  rabbitmq:
    stations-exchange: stations
    temperature-routing-key: stations.temperature
    wind-routing-key: stations.wind